services:
  testagent:
    image: localhost:5001/testagent:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uv", "run", "testagent", "--local"]
    ports:
      - "8080:8080"
    environment:
      - OTEL_SERVICE_NAME=testagent
      - AWS_REGION=us-west-2
      - MODEL_NAME=us.amazon.nova-lite-v1:0
      - AGENTCORE_RUNTIME_ARN=arn:aws:bedrock-agentcore:us-west-2:802411188784:runtime/yuval_kechomcp-NWSkxf7ZhI
