# AUTOGENERATED FILE: DO NOT EDIT
# Generated by the AgentRegistry CLI.

ARG DOCKER_REGISTRY=ghcr.io
ARG VERSION=0.7.12
FROM $DOCKER_REGISTRY/kagent-dev/kagent/kagent-adk:$VERSION

WORKDIR /app

COPY testagent/ testagent/
COPY pyproject.toml pyproject.toml
COPY README.md README.md
COPY .python-version .python-version

RUN uv sync

ENV OTEL_SERVICE_NAME=testagent

CMD ["testagent"]

